        # this is the real project file where all the team member will add there code



          TASK 1 (TEAM 1)

1.TASK1.1 UI DEVELOPMENT COMPLETED :THIS IS THE SOURCE CODE.
2.Task 1.2 completed BACKEND DEVELOPMENT TEAM : THIS IS THE SOURCE CODE.
3. Task 1.3 completed BACKEND DEVELOPMENT TEAM : THIS IS THE SOURCE CODE.
4.TASK 1.4 completed TEST AND DEBUG TEAM: THIS IS THE SOURCE CODE.
5.TASK 1.5 COMPLETED TEST AND DEBUG TEAM: THIS IS THE SOURCE CODE.


             TAST 4 (TEAM1)

1. TASK 4.1 UI DEVELOPMENT TEAM :THIS IS THE SOURCE CODE.
2.TASK 4.2 BACKEND TEAM :THIS IS THE SOURCE CODE.
